name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get commits between tags
        id: commits
        run: |
          PREV_TAG=$(git tag --list "v[0-9]*" --sort=-v:refname | grep -Ev "rc|beta|alpha" | head -n 1)
          CURRENT_TAG=${{ github.ref_name }}
          if [ "$PREV_TAG" = "$CURRENT_TAG" ]; then
            PREV_TAG=$(git tag --list "v[0-9]*" --sort=-v:refname | grep -Ev "rc|beta|alpha" | head -n 2 | tail -n 1)
          fi
          echo "prev_tag=$PREV_TAG" >> $GITHUB_OUTPUT
          
          # Correctly handle multi-line output
          commits=$(git log --pretty=format:'- %s' $PREV_TAG..HEAD | sed 's/[^[:print:]]//g')
          echo "commits<<EOF" >> $GITHUB_OUTPUT
          echo "$commits" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Replace version tag
        env:
          CURRENT_TAG: ${{ github.ref_name }}
        run: |
          # 使用井号(#)作为分隔符避免路径冲突
          find . -type f -name '*.ps1' -exec sed -i "s#DEFAULT_UPDATE_TOOLS_VERSION_TAG#$CURRENT_TAG#g" {} +
          find . -type f -name '*.py' -exec sed -i "s#DEFAULT_UPDATE_TOOLS_VERSION_TAG#$CURRENT_TAG#g" {} +
          find Linux/ -type f -name 'wanxiang-update' -exec sed -i "s#DEFAULT_UPDATE_TOOLS_VERSION_TAG#$CURRENT_TAG#g" {} +

      - name: Rename files
        run: |
          find Windows/ -type f -name '*.ps1' -exec bash -c 'mv "$0" "$(dirname "$0")/$(basename "$0" | sed "s/按需下载万象方案-词库-模型/rime-wanxiang-update-windows/")"' {} \;
          find Windows/ -type f -name '*.py' -exec bash -c 'mv "$0" "$(dirname "$0")/$(basename "$0" | sed "s/按需下载万象方案-词库-模型/rime-wanxiang-update-windows/")"' {} \;
          iconv -f utf-8 -t gbk Windows/PowerShell/rime-wanxiang-update-windows-utf-8.ps1 > Windows/PowerShell/rime-wanxiang-update-windows.ps1
          mv Linux/Shell/wanxiang-update Linux/Shell/rime-wanxiang-update-linux
          mv Win-Mac-iOS融合版\(Python\)/Python/万象下载更新.py Win-Mac-iOS融合版\(Python\)/Python/rime-wanxiang-update-win-mac-ios.py
          find basic/ -type f -name '*.ps1' -exec bash -c 'mv "$0" "$(dirname "$0")/$(basename "$0" | sed "s/按需下载万象方案-词库-模型-基础版/rime-wanxiang-update-windows-for-basic/")"' {} \;
          iconv -f utf-8 -t gbk basic/Windows/PowerShell/rime-wanxiang-update-windows-for-basic-utf-8.ps1 > basic/Windows/PowerShell/rime-wanxiang-update-windows-for-basic.ps1

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: |
            Changes since ${{ steps.commits.outputs.prev_tag }}:
            ${{ steps.commits.outputs.commits }}
          prerelease: ${{ contains(github.ref_name, '-rc') }}
          files: |
            Windows/PowerShell/rime-wanxiang-update-windows.ps1
            Windows/PowerShell/rime-wanxiang-update-windows-utf-8.ps1
            Windows/Python/rime-wanxiang-update-windows.py
            Linux/Shell/rime-wanxiang-update-linux
            basic/Windows/PowerShell/rime-wanxiang-update-windows-for-basic.ps1
            basic/Windows/PowerShell/rime-wanxiang-update-windows-for-basic-utf-8.ps1
            Win-Mac-iOS融合版\(Python\)/Python/rime-wanxiang-update-win-mac-ios.py
